packages:
  - 'packages/*'
  - 'apps/*'

overrides:
  drizzle-orm: "^0.45.2"
  "@types/react": "^19.0.0"
  "@types/react-dom": "^19.0.0"

peerDependencyRules:
  ignoreMissing:
    - "@types/react"
    - "@types/react-dom"
